// Generated by dedot cli

import type {
  ConstructorCallOptions,
  ContractInstantiateResult,
  GenericConstructorCallResult,
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  MetadataType,
} from 'dedot/contracts'
import type { GenericSubstrateApi } from 'dedot/types'

export interface ConstructorQuery<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericConstructorQuery<ChainApi, Type> {
  /**
   * Constructor that initializes the `bool` value to the given `init_value`.
   *
   * @param {boolean} initValue
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   */
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      initValue: boolean,
      options?: ConstructorCallOptions,
    ) => Promise<
      GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>
    >,
    Type
  >
}
