name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request with a focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Note: The PR branch is already checked out in the current working directory.

            IMPORTANT COMMENTING RULES:
            - Use `gh pr comment` for ONLY ONE concise top-level feedback comment per PR
            - Do NOT use inline comments - consolidate all feedback into a single brief GitHub comment
            - Keep the comment SHORT and to the point
            - Before posting a top-level comment, check if one already exists from previous runs
            - If a top-level comment exists, EDIT the existing comment instead of creating a new one
            - If no top-level comment exists, create a new one with `gh pr comment`
            - Focus on the most critical issues only - don't list every minor detail
            - Only post GitHub comments - don't submit review text as messages

            ADDITIONAL TASK:
            After completing the code review, also update the PR description with a brief summary.
            - Keep it very SHORT and concise (under 100 words)
            - Do NOT edit or modify the existing "## Context" section
            - Add your summary BELOW the existing "## Context" section
            - Focus only on key changes and critical points
            - Use `gh pr edit` to update the description

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: |
            --allowedTools "Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr edit:*)"
