name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request with a focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Note: The PR branch is already checked out in the current working directory.

            CRITICAL: YOU MUST CREATE EXACTLY ONE TOP-LEVEL COMMENT. NEVER CREATE MULTIPLE COMMENTS.

            MANDATORY COMMENTING WORKFLOW - NO EXCEPTIONS:
            1. ALWAYS start by running: `gh pr view ${{ github.event.pull_request.number }} --json comments --jq '.comments[] | select(.body | contains("## Claude Code Review")) | .id'`
            2. Store the result in a variable: EXISTING_COMMENT_ID
            3. IF EXISTING_COMMENT_ID is not empty:
               - Use ONLY: `gh pr comment $EXISTING_COMMENT_ID --edit --body "NEW_CONTENT"`
               - NEVER create a new comment
            4. IF EXISTING_COMMENT_ID is empty:
               - Use ONLY: `gh pr comment ${{ github.event.pull_request.number }} --body "CONTENT"`
               - Create exactly ONE comment
            5. MANDATORY: ALL comments must start with "## Claude Code Review" header
            6. FORBIDDEN: Never use `gh pr comment` without explicit comment ID when editing
            7. FORBIDDEN: Never create multiple comments under any circumstances

            VERIFICATION STEP:
            After commenting, run `gh pr view ${{ github.event.pull_request.number }} --json comments --jq '.comments[] | select(.body | contains("## Claude Code Review")) | length'` to verify only 1 Claude comment exists.

            COMMENT REQUIREMENTS:
            - Keep under 200 words
            - Focus on critical issues only
            - Single consolidated comment only
            - Must start with "## Claude Code Review"

            ADDITIONAL TASK:
            After commenting, update the PR description:
            - Use `gh pr edit ${{ github.event.pull_request.number }} --body` to append a brief summary (under 100 words)
            - Do NOT modify existing "## Context" section
            - Add summary BELOW existing content
            - Focus on key changes only

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: |
            --allowedTools "Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr edit:*)"
