name: CLI E2E Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'cli/**'
      - '.github/workflows/cli-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'cli/**'
      - '.github/workflows/cli-tests.yml'

jobs:
  cli-tests:
    name: CLI E2E Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22]
        exclude:
          # Reduce matrix size by excluding some combinations
          - os: windows-latest
            node-version: 18
          - os: macos-latest
            node-version: 18

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: cli
        run: bun install

      - name: Lint code
        working-directory: cli
        run: bun run lint

      - name: Build CLI
        working-directory: cli
        run: bun run build

      - name: Run E2E tests
        working-directory: cli
        run: bun run test
        env:
          # Ensure telemetry is disabled during CI
          DISABLE_TELEMETRY: 'true'
          # Force non-interactive mode
          CI: 'true'

      - name: Upload test artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            cli/dist/
            /tmp/create-dot-app-test-*
          retention-days: 3
