name: Package Managers

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check for template changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            next-dedot:
              - 'templates/next-dedot/**'
            next-papi:
              - 'templates/next-papi/**'
            nuxt-dedot:
              - 'templates/nuxt-dedot/**'
            nuxt-papi:
              - 'templates/nuxt-papi/**'
            react-dedot:
              - 'templates/react-dedot/**'
            react-papi:
              - 'templates/react-papi/**'
            vue-dedot:
              - 'templates/vue-dedot/**'
            vue-papi:
              - 'templates/vue-papi/**'

  node:
    needs: changes
    if: ${{ needs.changes.outputs.templates != '[]' && needs.changes.outputs.templates != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: ${{ fromJSON(needs.changes.outputs.templates) }}
        include:
          - template: next-dedot
            working-directory: templates/next-dedot
          - template: next-papi
            working-directory: templates/next-papi
          - template: nuxt-dedot
            working-directory: templates/nuxt-dedot
          - template: nuxt-papi
            working-directory: templates/nuxt-papi
          - template: react-dedot
            working-directory: templates/react-dedot
          - template: react-papi
            working-directory: templates/react-papi
          - template: vue-dedot
            working-directory: templates/vue-dedot
          - template: vue-papi
            working-directory: templates/vue-papi
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies with npm
        working-directory: ${{ matrix.working-directory }}
        run: npm install

      - name: Lint code
        working-directory: ${{ matrix.working-directory }}
        run: npm run lint

      - name: Build project with npm
        working-directory: ${{ matrix.working-directory }}
        run: npm run build

  deno:
    needs: changes
    if: ${{ needs.changes.outputs.templates != '[]' && needs.changes.outputs.templates != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: ${{ fromJSON(needs.changes.outputs.templates) }}
        include:
          - template: react-dedot
            working-directory: templates/react-dedot
          - template: react-papi
            working-directory: templates/react-papi
          - template: vue-dedot
            working-directory: templates/vue-dedot
          - template: vue-papi
            working-directory: templates/vue-papi
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies with Deno
        working-directory: ${{ matrix.working-directory }}
        run: deno install

      - name: Run postinstall with Deno
        if: contains(matrix.working-directory, 'papi')
        working-directory: ${{ matrix.working-directory }}
        run: deno run postinstall

      - name: Lint code with Deno
        working-directory: ${{ matrix.working-directory }}
        run: deno task lint

      - name: Build project with Deno
        working-directory: ${{ matrix.working-directory }}
        run: deno task build
