name: Package Managers

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-manager: [npm, pnpm, bun]
        working-directory: [cli/templates/vue-papi]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Setup pnpm
        if: matrix.package-manager == 'pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Bun
        if: matrix.package-manager == 'bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies with ${{ matrix.package-manager }}
        working-directory: ${{ matrix.working-directory }}
        run: |
          case "${{ matrix.package-manager }}" in
            npm)
              npm install
              ;;
            pnpm)
              pnpm install
              ;;
            bun)
              bun install
              ;;
          esac

      - name: Lint code
        working-directory: ${{ matrix.working-directory }}
        run: |
          case "${{ matrix.package-manager }}" in
            npm)
              npm run lint
              ;;
            pnpm)
              pnpm run lint
              ;;
            bun)
              bun run lint
              ;;
          esac

      - name: Build project with ${{ matrix.package-manager }}
        working-directory: ${{ matrix.working-directory }}
        run: |
          case "${{ matrix.package-manager }}" in
            npm)
              npm run build
              ;;
            pnpm)
              pnpm run build
              ;;
            bun)
              bun run build
              ;;
          esac

 